### ISSUE TITLE
Empty/Cleared Interface when time ruler is moved to another window

### ISSUE THREAD

**Issue by JomTansen** [j-palindrome/obsidian-time-ruler#102] opened 2024-03-15 11:23 UTC
**Describe the bug**
When time ruler is moved outside of the main obsidian window to create a second/new window, the interface gets cleared and shows no clicklable elements.

**To Reproduce**
1. Click on "Open Time Ruler"
2. Right click on the Time Ruler Icon
3. Click "Move to new window"
4. Drag a task somehwere
5. -> Here is where the bug / empty screen happens.

**Expected behavior**
I would expect the time ruler interface to work in a secondary window.

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/19568414/f149f3a8-4f23-41a9-a2b9-66fc30b59583)

**Obsidian Version:** 
- [ ] Desktop 1.5.8

**Comment by joshuatazrein** [comment] 2024-03-20 18:59
I agree, this is probably a bug on loading and it's hard to reproduce. Are there any console messages?

**Comment by j-palindrome** [comment] 2024-06-02 03:35
I'm asking the developer community because this is an issue with global Obsidian window events.

**Comment by j-palindrome** [comment] 2024-09-28 14:46
This has been fixed in v2.5.0.

**Closed by j-palindrome** 2024-09-28 14:46 UTC
